# Generated by Django 5.1.6 on 2025-03-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cources',
            fields=[
                ('cource_name', models.CharField(max_length=50)),
                ('active', models.CharField(max_length=10)),
                ('img', models.ImageField(blank=True, null=True, upload_to='course_images')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cources',
            },
        ),
    ]
